config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :employees, only: [:index]

  namespace :api do
    resources :employees, only: [:index]
    resources :departments, only: [:index]
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/controllers/api/departments_controller.rb
module Api
  class DepartmentsController < ApplicationController
    def index
      @departments = [
        { name: 'WATER MGMNT' },
        { name: 'POLICE' },
        { name: 'GENERAL SERVICES' },
        { name: 'CITY COUNCIL' },
        {name: 'STREETS & SAN'},
        {name: 'AVIATION'},
        {name: 'FIRE'},
        {name: 'FAMILY & SUPPORT'},
        {name: 'IPRA'},
        {name: 'BUSINESS AFFAIRS'},
        {name: 'OEMC'},
        {name: 'TRANSPORTN'},
        {name: 'HEALTH'},
        {name: 'MAYOR\'S OFFICE'},
        {name: 'LAW'}
      ]
      render json: @departments
    end
  end
end

app/controllers/api/employees_controller.rb
module Api
  class EmployeesController < ApplicationController
    def index
      render json: @employees = Employee.all.limit(1000);
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all.limit(10).to_json
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/index.html.erb
<div class="panel" ng-controller="employeesCtrl" ng-init="init({ employees: <%= @employees %> })">

<ul class="pager">
  <li class="previous"><a href="">&larr; Previous Page</a></li>
  <li><input ng-model="deptQuery" placeholder="Department"></li>
  <span class="label label-primary">Page: {{ page }}</span>
  <li class="next"><a href="">Next Page &rarr;</a></li>
</ul>

  <ul class="list-group">
    <li class="list-group-item" ng-repeat="employee in employees | filter:{ department: deptQuery }">
    <span>{{ employee.name }}</span>
    <span class="pull-right">{{ employee.department }}</span>
    <span>{{ employee.title }}</span>
    <p> <strong>Annual Salary:</strong> {{ employee.salary | currency }}</p>
    </li>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChicagoEmployees</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <a class="navbar-brand" href="/">Chicago Employees</a>
  </div>
</nav>

<div class="container" ng-app="app">
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Chicago Open Employee Data</h1>

  <p>This dataset is a listing of all current City of Chicago employees, complete with full names, departments, positions, and annual salaries.</p>

  <p><%= link_to "See List", employees_url, class: "btn btn-primary btn-lg" %></p>
</div>